extends: [[spectral:oas, all]]

rules:
  operation-operationId-unique: error
  operation-parameters: error
  contact-properties: error
  openapi-tags: error
  openapi-tags-alphabetical: error
  openapi-tags-uniqueness: error
  license-url: error
  info-license: error
  oas3-server-not-example.com: error
  oas3-operation-security-defined: error
  oas3-parameter-description: error
  oas3-callbacks-in-callbacks: error
  path-declarations-must-exist: error
  operation-singular-tag: error
  tag-description: error
  no-eval-in-markdown: error
  no-script-tags-in-markdown: warn
  duplicated-entry-in-enum: warn
  oas3-schema: warn
  array-items: warn
  path-not-include-query: warn
  oas3-server-variables: warn
  oas3-examples-value-or-externalValue: warn
  operation-operationId-valid-in-url: hint
  typed-enum: hint
  oas3-api-servers: hint
  operation-success-response: hint
  path-params: hint
  info-contact: hint
  operation-tag-defined: hint
  oas3-valid-media-example: hint
  no-$ref-siblings: hint
  path-keys-no-trailing-slash: hint
  operation-description: hint
  oas3-valid-schema-example: hint
  oas3-unused-component: hint
  operation-operationId: hint
  info-description: hint
  operation-tags: hint
  oas3-server-trailing-slash: hint
